name: Release Build and Deploy

on:
  push:
    tags:
      - 'v*.*.*'  # Executa ao fazer push de uma tag de versão, como v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload JAR as release artifact
        uses: actions/upload-artifact@v2
        with:
          name: myapp.jar
          path: target/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: target/*.jar
          asset_name: myapp.jar
          asset_content_type: application/java-archive
